# Generated by Django 6.0.7 on 2026-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_loancalculation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancalculation',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
